'use client';

import { usePathname } from 'next/navigation';
import Head from 'next/head';
import { useEffect, useState } from 'react';

interface SeoMetaProps {
  title?: string;
  description?: string;
  keywords?: string;
  ogImage?: string;
  ogType?: string;
  twitterCard?: string;
}

export default function SeoMeta({
  title,
  description,
  keywords,
  ogImage = '/og-image.svg',
  ogType = 'website',
  twitterCard = 'summary_large_image',
}: SeoMetaProps) {
  const pathname = usePathname();
  const [pageTitle, setPageTitle] = useState(title);
  const [pageDescription, setPageDescription] = useState(description);
  const [pageKeywords, setPageKeywords] = useState(keywords);

  useEffect(() => {
    // Set default meta data based on the current page
    if (!pathname) return;

    if (!title) {
      if (pathname === '/') {
        setPageTitle('Nexus AI Consulting - AI-Powered Business Solutions in 15 Minutes | Affordable Strategy Consulting');
      } else if (pathname === '/solutions') {
        setPageTitle('Business Solutions - Nexus AI Consulting | Strategy, Operations & Digital Transformation');
      } else if (pathname === '/ai-tools') {
        setPageTitle('AI Tools - Nexus AI Consulting | Advanced Business Intelligence & Analytics');
      } else if (pathname === '/pricing') {
        setPageTitle('Pricing - Nexus AI Consulting | Affordable AI-Powered Business Consulting');
      } else if (pathname.startsWith('/reports')) {
        setPageTitle('Business Reports - Nexus AI Consulting | Data-Driven Insights');
      } else {
        setPageTitle('Nexus AI Consulting - AI-Powered Business Solutions');
      }
    }

    if (!description) {
      if (pathname === '/') {
        setPageDescription('Revolutionary AI-powered consulting platform delivering McKinsey-quality insights in just 15 minutes. Affordable, fast, and easy-to-use business strategy, digital transformation, and operational excellence solutions for modern enterprises.');
      } else if (pathname === '/solutions') {
        setPageDescription('Explore our AI-powered business solutions for strategy development, market intelligence, operational excellence, and financial analysis. Get McKinsey-quality insights in minutes.');
      } else if (pathname === '/ai-tools') {
        setPageDescription('Discover our suite of AI-powered business tools for data analysis, market research, competitive intelligence, and strategic planning. Transform your business with cutting-edge AI technology.');
      } else if (pathname === '/pricing') {
        setPageDescription('Affordable pricing plans for AI-powered business consulting. Get McKinsey-quality insights at 1/100th the cost of traditional consulting services.');
      } else if (pathname.startsWith('/reports')) {
        setPageDescription('Access comprehensive business reports generated by our AI-powered platform. Data-driven insights and actionable recommendations for your business challenges.');
      } else {
        setPageDescription('AI-powered business consulting platform delivering McKinsey-quality insights in minutes. Transform your business with affordable, fast, and accurate consulting services.');
      }
    }

    if (!keywords) {
      if (pathname === '/') {
        setPageKeywords('AI consulting, business strategy, digital transformation, operational excellence, McKinsey-quality insights, affordable consulting, business solutions, AI-powered consulting, strategy consulting, business intelligence');
      } else if (pathname === '/solutions') {
        setPageKeywords('business solutions, strategy development, market intelligence, operational excellence, financial analysis, AI consulting, business transformation, strategic planning');
      } else if (pathname === '/ai-tools') {
        setPageKeywords('AI tools, business intelligence, data analysis, market research, competitive intelligence, strategic planning, business analytics, AI technology');
      } else if (pathname === '/pricing') {
        setPageKeywords('consulting pricing, affordable consulting, AI consulting cost, business strategy pricing, consulting plans, subscription pricing');
      } else if (pathname.startsWith('/reports')) {
        setPageKeywords('business reports, AI-generated reports, data-driven insights, business analysis, strategic recommendations, business intelligence reports');
      } else {
        setPageKeywords('AI consulting, business strategy, digital transformation, operational excellence, business solutions, AI-powered consulting');
      }
    }
  }, [pathname, title, description, keywords]);

  const canonicalUrl = `https://nexusaiconsulting.com${pathname}`;

  return (
    <Head>
      {/* Primary Meta Tags */}
      {pageTitle && <title>{pageTitle}</title>}
      {pageDescription && <meta name="description" content={pageDescription} />}
      {pageKeywords && <meta name="keywords" content={pageKeywords} />}
      
      {/* Canonical Link */}
      <link rel="canonical" href={canonicalUrl} />
      
      {/* Open Graph / Facebook */}
      <meta property="og:type" content={ogType} />
      {pageTitle && <meta property="og:title" content={pageTitle} />}
      {pageDescription && <meta property="og:description" content={pageDescription} />}
      <meta property="og:url" content={canonicalUrl} />
      <meta property="og:image" content={`https://nexusaiconsulting.com${ogImage}`} />
      
      {/* Twitter */}
      <meta name="twitter:card" content={twitterCard} />
      {pageTitle && <meta name="twitter:title" content={pageTitle} />}
      {pageDescription && <meta name="twitter:description" content={pageDescription} />}
      <meta name="twitter:image" content={`https://nexusaiconsulting.com${ogImage}`} />
    </Head>
  );
}